apiVersion: apps/v1
kind: Deployment
metadata:
  name: authoritative-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authoritative-server
  template:
    metadata:
      labels:
        app: authoritative-server
    spec:
      containers:
      - name: authoritative-server
        image: aygunnajafova/dns_app/as:latest 
        ports:
        - containerPort: 53533
---
apiVersion: v1
kind: Service
metadata:
  name: authoritative-service
spec:
  type: NodePort
  selector:
    app: authoritative-server
  ports:
  - port: 53533
    protocol: UDP
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-server
  template:
    metadata:
      labels:
        app: fibonacci-server
    spec:
      containers:
      - name: fibonacci-server
        image: aygunnajafova/dns_app/fs:latest 
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
spec:
  type: NodePort
  selector:
    app: fibonacci-server
  ports:
  - port: 9090
    protocol: TCP
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-server
        image: aygunnajafova/dns_app/us:latest 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-server
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30003
